dist: trusty
group: beta
sudo: false
language: node_js
node_js:
- lts/boron
deploy:
  provider: npm
  email: npm@collaborne.com
  api_key:
    secure: P24YshtsEvTHuwWEuzrN2jbCXJTvuXhQix0NnW2/Vsg7mUWP12thQSfCa+eX4b98rqwuDBN5phoz+QaMWuztRe7OKDGsua5hJlujAbcoiL34Z1Dv6ILTdPksnO1NaAR9R4nHKfz3XFksoHJLOIXBgbCn2B/4jmoreCLDTY6jjY08Jqym59sFQZazSt2eMDB3Xgn7s9iY6mkpRbeU+CrMTv8BDYXaWzrb2mrO2B/i1N1Izg4TOKz+1ShiQPp0ghQUyXVP4Z9VGaruo5BL84ZRkocCh+3C9ilwo98TLFMAq9a/2mLCVv/K2fnJf9WD/wKWFjzMpCgC1fxtqeKbBFFVK+PZ7U/G0gCjyboSNMAIIr1w5A/3F7CYIffGfWySDbd+l5juaaUbQQL0hnZ/3ZZYYEAcryLxKOlU8E+UYeqGnIIqkaVKRrURGbmuJigqokYzKFSvID+S1AHBqZ4g8XIlCFiyf6+f6k/Y2VSaDnZnf6vettevd0lGN3Aws+CoGeSvIv5s/gjnX+rot/SlFkopF680q+xW/fH37VwyVqByeBtWGFQHzxNrRpCucDY4t67aHCMvjYNPOqOI2ODP45500qBR/uRN1h5HRYgl/mgcH+nQ/apeKQuyfJ60MlW7uBMUAHxjXkSCVde8j0ZjEU0dhcKgBXwfDSAGBzm44NGUAcA=
  on:
    tags: true
