dist: trusty
group: beta
sudo: false
language: node_js
node_js:
- lts/boron
deploy:
  provider: npm
  email: npm@collaborne.com
  api_key:
    secure: KQxDZK4LVY1xisFoNFWVz9nhXe6fP8s53N5fapld5mdv5RS62NV6oUdTGTQViEcqt4XEMW133aeSOhvk9PNAwzdNkiKd8fHrwCCw2l4Bl7tgmsLnttOPIXlsjwUqaZXL4/UcfDPiOrgw3nWCC7u9R5XLV51xYNPcN/GYSZFGYuAe+rYMKl6rfIqviZVWwim2vIAskfLIColl75GU7NytXrxraf4K8WVKAK53LquAHGntJxgqWWg79LoyoQGukNmCm/yf0+2o5oR9IEjL4mDzUttyc2crjNm5qkM4NWt7LXt9OiUhHJCffTdbWXShK1eXyqhmFs5J7faR/SiOU5G4PwNL9l/6lqdrhKKL5NYUsZeXUXN3kReDPs4Oyy4WHGDnEMaQfqR/2ItTHF0sA4qWniCzb/kcJbmhksFV+s3VyRb5m4nZABC4qcv+jf1q8Va/c72Gnlh5aJWohqKIvOxWolrgEG96KTcGQqvN5+FMnTpAAwpLbKQPjJQvXhIZCXgJeQ6yD6/jX3Hv7I/p2USz4J0oSB7OfiaqZViSGtn4v8/c/FG8U1Ji6QEG30eFrnweuU9bmRPtwx6j7k0lzcRu4gStE/+rn9F/KLW/00aRLvuucbCZ2QAzAGbKL+bgPBOlh5TwZonX8Ds9mHugbwHAyXzsdWjxakI/3cmJZ8Mbpaw=
  on:
    tags: true
    repo: Collaborne/kinesis-stream-reader
